[workspace]
members = ["db"]
[package]
name = "turning_display"
version = "0.1.0"
edition = "2021"

[dependencies]
db = { path = "./db" }
lcd_driver = { path = "./lcd_driver" }
rppal = "0.19.0"
crossbeam = "0.8.4"
colors-transform = "0.2.11"
sk6812_rpi = "0.1.2"
rand = "0.8.5"